### ISSUE TITLE
Bring in raoutdoors development.services.yml

### ISSUE THREAD

**Issue by ao5357** [commercialprogression/symmetri_drupal#1]
To more quickly facilitate template development and the like, use the service yaml file from that project. It's a good starting point for further customization.

**Comment by hillylew** [comment]
https://github.com/commercialprogression/symmetri_drupal/commit/0f6f8bc779c97a523488d0477e6190120c42c8cf Added a good file in the sites/default directory so that a core update wouldn't override it (as it tends to do) and updated the pointer in settings.local.php
